easy_admin:
    site_name: 'Backend'
    user:
        display_name: true
        display_avatar: true
        name_property_path: 'username'
        avatar_property_path: 'gravatar'
    entities:
        User:
            class: App\Entity\User
            list:
                title: 'User'
                actions: ['new']
                fields:
                    - { property: 'id' }
                    - { property: 'email' ,type: 'email'}
                    - { property: 'image', template: 'images/image.html.twig' }
                    - { property: 'roles' }
                    - { property: 'createdBy' }
                    - { property: 'createdAt' }
                    - { property: 'updatedBy' }
                    - { property: 'updatedAt' }
            new:
                fields:
                    - { property: 'email' ,type: 'email'}
                    - { property: 'password',type: 'password' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'roles' }
            edit:
                fields:
                    - { property: 'email' ,type: 'email'}
                    - { property: 'password',type: 'password' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'roles' }     
        Advertising:
            class: App\Entity\Advertising
            list:
                title: 'Advertising'
                actions: ['new']
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'body' }
                    - { property: 'image', template: 'images/image.html.twig' }
                    - { property: 'published' }
                    - { property: 'tags' }
                    - { property: 'createdBy' }
                    - { property: 'createdAt' }
                    - { property: 'updatedBy' }
                    - { property: 'updatedAt' }

            new:
                fields:
                    - { property: 'title' }
                    - { property: 'body' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'published' }   
                    - { property: 'tags' } 
            edit:
                fields:
                    - { property: 'title' }
                    - { property: 'body' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'published' } 
                    - { property: 'tags' }     
        Tag:
            class: App\Entity\Tag
            list:
                title: 'Tag'
                actions: ['new']
                fields:
                    - { property: 'id' }
                    - { property: 'name' }

            new:
                fields:
                    - { property: 'name' }
            edit:
                fields:
                    - { property: 'name' }


