vich_uploader:
    db_driver: orm
    
    mappings:
        ads_images:
            uri_prefix: /images/ads
            upload_destination: '%kernel.project_dir%/public/images/ads'
            inject_on_load: true
        user_images:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
